
CREATE TABLE UserTable (
Id VARCHAR(100),
Name VARCHAR(200),
Password VARCHAR(200),
isDeleted VARCHAR(200) DEFAULT "0",
Email VARCHAR(300) UNIQUE,
Role VARCHAR(100) DEFAULT 'user',
isSent VARCHAR(150) DEFAULT '0'
)

USE Client
DROP TABLE UserTable
SELECT * FROM UserTable